server:
  port: 8080

# swagger config

swagger:
  enabled: true
  title: demo接口文档
  version: dev
  base-package: com.zy

spring:
  jmx:
    enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.163.205:3306/practice?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: likun19951114
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 1800000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      connection-init-sqls: SET NAMES utf8mb4
# mybatis config
mybatis:
  type-aliases-package: com.zy.entity
  mapper-locations: classpath*:mappings/*.xml
  configuration:
    map-underscore-to-camel-case: true
